import { createHash, randomBytes } from "crypto";
import { ForbiddenException, Injectable, Logger, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";

export type SmtpCredentialSummary = {
  id: string;
  name: string;
  username: string;
  prefix: string;
  status: string;
  domain: string | null;
  createdAt: string;
  lastUsedAt: string | null;
  lastUsedIp: string | null;
  rotatedAt: string | null;
};

export type SmtpCredentialCreated = {
  credential: SmtpCredentialSummary;
  /** Returned exactly once. We store only a hash, so this cannot be recovered. */
  password: string;
};

const SECRET_PREFIX = "nani_smtp_";

/**
 * Story 4: customer-managed SMTP credentials.
 *
 * Replaces the in-memory map in SmtpService, which lost every credential on
 * restart and only ever held one per workspace.
 *
 * Secrets are 192 bits of randomness generated by us, so a single SHA-256 is an
 * adequate verifier — no password stretching is needed for a value no one
 * chose, and the relay has to check it on every AUTH command, so speed matters.
 * The same hash function is used by SmtpAuthService, deliberately: credentials
 * issued here must verify at the relay without a translation step.
 */
@Injectable()
export class SmtpCredentialsService {
  private readonly logger = new Logger(SmtpCredentialsService.name);

  constructor(private readonly prisma: PrismaService) {}

  static hashSecret(secret: string): string {
    return createHash("sha256").update(secret).digest("hex");
  }

  async list(tenantId: string): Promise<SmtpCredentialSummary[]> {
    const rows = await this.prisma.smtpCredential.findMany({
      where: { tenantId, status: { not: "REVOKED" } },
      include: { domain: { select: { name: true } } },
      orderBy: { createdAt: "desc" },
    });

    return rows.map((row: CredentialRow) => this.toSummary(row));
  }

  /**
   * Issue a credential. Optionally scoped to one domain — a domain-scoped
   * credential can only send as that domain, which is what you want for a
   * per-application key.
   */
  async create(
    tenantId: string,
    userId: string,
    input: { name?: string; domainId?: string },
  ): Promise<SmtpCredentialCreated> {
    const domain = input.domainId ? await this.requireOwnedDomain(input.domainId, tenantId) : null;

    // Username carries the domain so it is self-describing in a mail client's
    // settings screen, where the customer has no other context.
    const localPart = domain ? `smtp-${randomBytes(3).toString("hex")}` : `smtp-${randomBytes(4).toString("hex")}`;
    const host = domain?.name ?? "nani.africa";
    const username = `${localPart}@${host}`;

    const password = `${SECRET_PREFIX}${randomBytes(24).toString("base64url")}`;

    const created = await this.prisma.smtpCredential.create({
      data: {
        name: input.name?.trim() || (domain ? `${domain.name} credential` : "Workspace credential"),
        username,
        prefix: password.slice(0, SECRET_PREFIX.length + 6),
        secretHash: SmtpCredentialsService.hashSecret(password),
        status: "ACTIVE",
        tenantId,
        domainId: domain?.id ?? null,
        createdById: userId,
      },
      include: { domain: { select: { name: true } } },
    });

    this.logger.log(`Issued SMTP credential ${username} for tenant ${tenantId}`);

    return { credential: this.toSummary(created), password };
  }

  /**
   * Rotate: issue a new secret for an existing credential, keeping the username
   * so the customer only has to change one field in their mail configuration.
   *
   * The old secret stops working immediately. That is the correct trade-off for
   * a rotation — a grace period would defeat the point when rotating because of
   * a suspected leak.
   */
  async rotate(id: string, tenantId: string, _userId: string): Promise<SmtpCredentialCreated> {
    const existing = await this.requireOwned(id, tenantId);

    const password = `${SECRET_PREFIX}${randomBytes(24).toString("base64url")}`;

    const updated = await this.prisma.smtpCredential.update({
      where: { id: existing.id },
      data: {
        prefix: password.slice(0, SECRET_PREFIX.length + 6),
        secretHash: SmtpCredentialsService.hashSecret(password),
        status: "ACTIVE",
        rotatedAt: new Date(),
        revokedAt: null,
      },
      include: { domain: { select: { name: true } } },
    });

    this.logger.log(`Rotated SMTP credential ${updated.username}`);

    return { credential: this.toSummary(updated), password };
  }

  /**
   * Revoke rather than delete: `EmailMessage.credentialId` points here, and the
   * audit trail of which credential sent what is worth more than a tidy table.
   */
  async revoke(id: string, tenantId: string): Promise<SmtpCredentialSummary> {
    const existing = await this.requireOwned(id, tenantId);

    const updated = await this.prisma.smtpCredential.update({
      where: { id: existing.id },
      data: { status: "REVOKED", revokedAt: new Date() },
      include: { domain: { select: { name: true } } },
    });

    this.logger.log(`Revoked SMTP credential ${updated.username}`);

    return this.toSummary(updated);
  }

  /* ---------------------------------------------------------------------- */

  private async requireOwned(id: string, tenantId: string): Promise<CredentialRow> {
    const row = await this.prisma.smtpCredential.findUnique({
      where: { id },
      include: { domain: { select: { name: true } } },
    });
    if (!row || row.tenantId !== tenantId) {
      throw new NotFoundException("Credential not found in this workspace.");
    }
    return row;
  }

  private async requireOwnedDomain(domainId: string, tenantId: string): Promise<{ id: string; name: string }> {
    const domain = await this.prisma.domain.findUnique({ where: { id: domainId } });
    if (!domain || domain.tenantId !== tenantId) {
      throw new ForbiddenException("That domain is not in this workspace.");
    }
    return { id: domain.id, name: domain.name };
  }

  private toSummary(row: CredentialRow): SmtpCredentialSummary {
    return {
      id: row.id,
      name: row.name,
      username: row.username,
      prefix: row.prefix,
      status: row.status,
      domain: row.domain?.name ?? null,
      createdAt: row.createdAt.toISOString(),
      lastUsedAt: row.lastUsedAt ? row.lastUsedAt.toISOString() : null,
      lastUsedIp: row.lastUsedIp ?? null,
      rotatedAt: row.rotatedAt ? row.rotatedAt.toISOString() : null,
    };
  }
}

type CredentialRow = {
  id: string;
  name: string;
  username: string;
  prefix: string;
  status: string;
  tenantId: string;
  createdAt: Date;
  lastUsedAt: Date | null;
  lastUsedIp: string | null;
  rotatedAt: Date | null;
  domain: { name: string } | null;
};
