import { createHash, randomBytes } from "crypto";
import { ForbiddenException, Injectable, Logger, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../prisma/prisma.service";

export type SmtpCredentialSummary = {
  id: string;
  name: string;
  username: string;
  prefix: string;
  status: string;
  domain: string | null;
  createdAt: string;
  lastUsedAt: string | null;
  lastUsedIp: string | null;
  rotatedAt: string | null;
};

export type SmtpCredentialCreated = {
  credential: SmtpCredentialSummary;
  /** Returned exactly once. We store only a hash, so this cannot be recovered. */
  password: string;
};

const SECRET_PREFIX = "nani_smtp_";

/**
 * Stories 4 and 11: customer-managed SMTP credentials, with the security
 * actions written to an audit log.
 *
 * Secrets are 192 bits of randomness generated by us, so a single SHA-256 is an
 * adequate verifier — no password stretching is needed for a value no human
 * chose, and the relay checks it on every AUTH command, so speed matters. The
 * hash function is deliberately identical to SmtpAuthService's: a credential
 * issued here must verify at the relay with no translation step.
 */
@Injectable()
export class SmtpCredentialsService {
  private readonly logger = new Logger(SmtpCredentialsService.name);

  constructor(private readonly prisma: PrismaService) {}

  static hashSecret(secret: string): string {
    return createHash("sha256").update(secret).digest("hex");
  }

  async list(tenantId: string): Promise<SmtpCredentialSummary[]> {
    const rows = await this.prisma.smtpCredential.findMany({
      where: { tenantId, status: { not: "REVOKED" } },
      include: { domain: { select: { name: true } } },
      orderBy: { createdAt: "desc" },
    });

    return rows.map((row: CredentialRow) => this.toSummary(row));
  }

  /**
   * Issue a credential. Optionally scoped to one domain — a domain-scoped
   * credential can only send as that domain, which is what you want for a
   * per-application key.
   */
  async create(
    tenantId: string,
    userId: string,
    input: { name?: string; domainId?: string },
  ): Promise<SmtpCredentialCreated> {
    const domain = input.domainId ? await this.requireOwnedDomain(input.domainId, tenantId) : null;

    // The username carries the domain so it is self-describing in a mail
    // client's settings screen, where the customer has no other context.
    const localPart = `smtp-${randomBytes(4).toString("hex")}`;
    const host = domain?.name ?? process.env.SMTP_DEFAULT_CREDENTIAL_HOST ?? "nani.africa";
    const username = `${localPart}@${host}`;
    const password = `${SECRET_PREFIX}${randomBytes(24).toString("base64url")}`;

    const created = await this.prisma.smtpCredential.create({
      data: {
        name: input.name?.trim() || (domain ? `${domain.name} credential` : "Workspace credential"),
        username,
        prefix: password.slice(0, SECRET_PREFIX.length + 6),
        secretHash: SmtpCredentialsService.hashSecret(password),
        status: "ACTIVE",
        tenantId,
        domainId: domain?.id ?? null,
        createdById: userId,
      },
      include: { domain: { select: { name: true } } },
    });

    await this.audit(tenantId, userId, "SMTP_CREDENTIAL_CREATED", username, { domain: domain?.name ?? null });

    return { credential: this.toSummary(created), password };
  }

  /**
   * Rotate: new secret, same username, so the customer changes one field in
   * their configuration rather than two.
   *
   * The old secret stops working immediately. That is the right trade-off for a
   * rotation — a grace period defeats the purpose when you are rotating because
   * you suspect a leak.
   */
  async rotate(id: string, tenantId: string, userId: string): Promise<SmtpCredentialCreated> {
    const existing = await this.requireOwned(id, tenantId);
    const password = `${SECRET_PREFIX}${randomBytes(24).toString("base64url")}`;

    const updated = await this.prisma.smtpCredential.update({
      where: { id: existing.id },
      data: {
        prefix: password.slice(0, SECRET_PREFIX.length + 6),
        secretHash: SmtpCredentialsService.hashSecret(password),
        status: "ACTIVE",
        rotatedAt: new Date(),
        revokedAt: null,
      },
      include: { domain: { select: { name: true } } },
    });

    await this.audit(tenantId, userId, "SMTP_CREDENTIAL_ROTATED", updated.username);

    return { credential: this.toSummary(updated), password };
  }

  /**
   * Story 4: disable is reversible, unlike revoke. Use it to switch off an
   * application temporarily without forcing the customer to reconfigure it with
   * a new secret afterwards.
   */
  async setEnabled(id: string, tenantId: string, userId: string, enabled: boolean): Promise<SmtpCredentialSummary> {
    const existing = await this.requireOwned(id, tenantId);

    if (existing.status === "REVOKED") {
      throw new ForbiddenException("A revoked credential cannot be re-enabled. Create a new one.");
    }

    const updated = await this.prisma.smtpCredential.update({
      where: { id: existing.id },
      data: { status: enabled ? "ACTIVE" : "DISABLED" },
      include: { domain: { select: { name: true } } },
    });

    await this.audit(
      tenantId,
      userId,
      enabled ? "SMTP_CREDENTIAL_ENABLED" : "SMTP_CREDENTIAL_DISABLED",
      updated.username,
    );

    return this.toSummary(updated);
  }

  /**
   * Revoke rather than delete: `EmailMessage.credentialId` points here, and
   * knowing which credential sent a message is worth more than a tidy table.
   */
  async revoke(id: string, tenantId: string, userId: string): Promise<SmtpCredentialSummary> {
    const existing = await this.requireOwned(id, tenantId);

    const updated = await this.prisma.smtpCredential.update({
      where: { id: existing.id },
      data: { status: "REVOKED", revokedAt: new Date() },
      include: { domain: { select: { name: true } } },
    });

    await this.audit(tenantId, userId, "SMTP_CREDENTIAL_REVOKED", updated.username);

    return this.toSummary(updated);
  }

  /* ---------------------------------------------------------------------- */

  /**
   * Story 11: "all security actions are written to an audit log."
   *
   * Best-effort on purpose — a failed audit write must not roll back the
   * revocation it was recording. Losing the log entry is bad; leaving a
   * compromised credential active because the log was unavailable is worse.
   */
  private async audit(
    tenantId: string,
    userId: string,
    action: string,
    subject: string,
    meta?: Record<string, unknown>,
  ): Promise<void> {
    try {
      await this.prisma.securityAuditLog.create({
          data: {
          tenantId,
          userId,
          action,
          entity: "SmtpCredential",
          entityId: subject,
          metadata: meta ? (meta as object) : undefined,
        },
      });
    } catch (error) {
      const detail = error instanceof Error ? error.message : "unknown";
      this.logger.warn(`Audit write failed for ${action} on ${subject}: ${detail}`);
    }
  }

  private async requireOwned(id: string, tenantId: string): Promise<CredentialRow> {
    const row = await this.prisma.smtpCredential.findUnique({
      where: { id },
      include: { domain: { select: { name: true } } },
    });
    if (!row || row.tenantId !== tenantId) {
      throw new NotFoundException("Credential not found in this workspace.");
    }
    return row;
  }

  private async requireOwnedDomain(domainId: string, tenantId: string): Promise<{ id: string; name: string }> {
    const domain = await this.prisma.domain.findUnique({ where: { id: domainId } });
    if (!domain || domain.tenantId !== tenantId) {
      throw new ForbiddenException("That domain is not in this workspace.");
    }
    return { id: domain.id, name: domain.name };
  }

  private toSummary(row: CredentialRow): SmtpCredentialSummary {
    return {
      id: row.id,
      name: row.name,
      username: row.username,
      prefix: row.prefix,
      status: row.status,
      domain: row.domain?.name ?? null,
      createdAt: row.createdAt.toISOString(),
      lastUsedAt: row.lastUsedAt ? row.lastUsedAt.toISOString() : null,
      lastUsedIp: row.lastUsedIp ?? null,
      rotatedAt: row.rotatedAt ? row.rotatedAt.toISOString() : null,
    };
  }
}

type CredentialRow = {
  id: string;
  name: string;
  username: string;
  prefix: string;
  status: string;
  tenantId: string;
  createdAt: Date;
  lastUsedAt: Date | null;
  lastUsedIp: string | null;
  rotatedAt: Date | null;
  domain: { name: string } | null;
};
